

platform :ios, '13.0'

target 'example_pod' do
  pod 'Coordinator', :path => '../'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for example_pod

  target 'example_podTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'example_podUITests' do
    # Pods for testing
  end

end
